---
on: [push, pull_request]
name: default

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nvim-versions: ['stable', 'nightly']
    name: test
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.nvim-versions }}

      - name: run tests
        run: ./run test

  stylua:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: format
        uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check lua tests

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: nightly

      - name: install lua-language-server
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd
          gh release download -R sumneko/lua-language-server -p '*-linux-x64.tar.gz' -D lua-language-server
          tar xzf lua-language-server/* -C lua-language-server
          echo "${PWD}/lua-language-server/bin" >> $GITHUB_PATH
          export PATH="${PWD}/lua-language-server/bin:${PATH}"
          lua-language-server --version

      - name: install luacheck
        run: |
          sudo apt-get update
          sudo apt-get install -y luarocks
          sudo luarocks install luacheck

      - name: lint
        run: ./run lint
